config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users do
    resources :messages
  end

  root "home#index"
  resources :messages
  resources :home

  resources :groups do
    resources :messages
  end
  
  post 'home/search', to: 'home#search', as: :search
  post 'groups/search', to: 'groups#search', as: :group_search
  get '/groups/:id/list_user', to: 'groups#list_user', as: :list_user
  post '/groups/:id/add_user', to: 'groups#add_user', as: :add_user_group
  delete '/groups/:id/remove_user', to: 'groups#remove_user', as: :remove_user_group

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :messages, as: :receiver, dependent: :destroy
  belongs_to :admin, class_name: "User", optional: true
  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 8 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :receiver, polymorphic: true
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :normalize_name
  has_one_attached :avatar
  has_and_belongs_to_many :groups
  has_many :messages, dependent: :destroy
  has_many :messages, as: :receiver, dependent: :destroy
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  enum :gender, { male: 0, female: 1, others: 2 }
  validates :name, presence: true, length: { minimum: 2 }
  validates :gender, presence: true



  private
  def normalize_name
    self.name = name.strip if name.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :group_admin?, only: [:edit, :update, :add_user, :remove_user, :destroy]
  before_action :group_user?, only: [:show]

  def list_user
    @group = Group.find(params[:id])
    @users = @group.users
  end

  def search
    @group = Group.find(params[:group_search][:group_id])
    @search = User.where("name LIKE ? OR email LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
                .where.not(id: @group.users.pluck(:id))
                .order("name ASC")
  end
  

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
    @group.admin = current_user

    if @group.save
      @group.users << current_user
      redirect_to @group, notice: "Group was successfully created."
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group, notice: "Group was successfully updated."
    else
      render :edit
    end
  end

  def add_user
    @group = Group.find(params[:id])
    @user = User.find(params[:user_id])
    @group.users << @user
    redirect_to @group
  end

  def remove_user
    @group = Group.find(params[:id])
    @user = User.find(params[:user_id])
    if @user == current_user
      flash[:error] = "You cannot remove yourself from the group."
    else
      @group.users.delete(@user)
      flash[:success] = "User removed from the group."
    end
    redirect_to @group
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to root_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end

  def group_admin?
    @group = Group.find(params[:id])
    unless current_user.id == @group.admin_id
      flash[:error] = "You do not have permission to access this page."
      redirect_to @group
    end
  end

  def group_user?
    @group = Group.find(params[:id])
    unless @group.users.include?(current_user)
      redirect_to root_path, alert: "You are not a member of this group."
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @msg_users = conversation
  end

  def search
    @search = User.where("name LIKE ? OR email LIKE ?",  "%#{params[:query]}%", "%#{params[:query]}%")
                  .where.not(id: current_user.id)
                  .order("name ASC")          
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def conversation
    @messages = Message.where(user_id: current_user.id).or(Message.where(receiver_id: current_user.id))

    @users = User.joins("INNER JOIN messages ON users.id = messages.user_id OR users.id = messages.receiver_id")
              .where(messages: { receiver_type: 'User', id: @messages.select(:id) })
              .where.not(id: current_user.id)
              .select("users.*, MAX(messages.created_at) AS latest_message_time, messages.id AS latest_message_id")
              .group("users.id")
              .order("latest_message_time DESC")
              .distinct
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    receiver_type = params[:message][:receiver_type]

    if receiver_type == "User"
      @message.receiver = User.find(params[:message][:receiver_id])
    elsif receiver_type == "Group"
      @message.receiver = Group.find(params[:message][:receiver_id])
    end

    
  
    if @message.save
      if receiver_type == "User"
        MessagesChannel.broadcast_to(@message.receiver, render_to_string(partial: "partial/message", 
          locals: { msg: @message, sender: @message.receiver }))
        MessagesChannel.broadcast_to(@message.user, render_to_string(partial: "partial/message", 
          locals: { msg: @message, sender: @message.user }))
        redirect_to home_path(@message.receiver)
      elsif receiver_type == "Group"
        GroupChannel.broadcast_to(@message.receiver, render_to_string(partial: "partial/message", 
          locals: { msg: @message, sender: @message.receiver }))
        redirect_to @message.receiver
      end
      
    else
      render  status: :unprocessable_entity
    end
  end
  

  private
  
  def message_params
    params.require(:message).permit(:content, :receiver, :receiver_type, :receiver_id, images: [] )
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name, :gender])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :name, :gender, :avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/groups/edit.html.erb
<%= turbo_frame_tag "space-content" do%>
  <div class="outer update-grp">
    <%= form_for(@group) do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, autocomplete: "off" %>
        <% if @group.errors[:name].any? %>
          <div class="text-danger">
            <%= @group.errors[:name].join(', ') %>
          </div>
        <% end %>
      </div>

      <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
        <% if @group.errors[:description].any? %>
          <div class="text-danger">
            <%= @group.errors[:description].join(', ') %>
          </div>
        <% end %>
      </div>

      <%= f.submit %>
    <% end %>
  </div>
<% end %>

app/views/groups/list_user.erb
<%= turbo_frame_tag "space-content" do%>
  <div class="participants-search">
    <%= form_for :group_search, url: 'groups/search', method: :post do |f| %>
      <%= f.hidden_field :group_id, value: @group.id %>
      <%= f.text_field :query, name: 'query', placeholder: 'Search', autocomplete: "off" %>
      <%= button_tag type: "submit", data: { turbo_frame: "participants-frame"} do %>
        <%= image_tag "Magnifier.png" %>
      <% end %>
    <% end %>
  </div>

  <div class="participants">
    <%= turbo_frame_tag "participants-frame" do %>
      <% @users.each do |u|%>
        <div class="participants-list">
          <div class="participants-list-avatar">
            <% if u.avatar.present?%>
              <%= image_tag url_for(u.avatar) %>
            <% else %>
              <% if u.gender == "male"%>
                <%= image_tag "male_avatar.png" %>
              <% else %>
                <%= image_tag "female_avatar.png" %>
              <% end %>
            <% end %>
          </div>

          <div class="participants-list-content">
            <%= u.name %><br>
            <%= u.email%>
          </div>

          <% if (current_user.id == @group.admin_id && current_user.id != u.id) %>
            <%= button_to remove_user_group_path(@group, user_id: u.id),
              method: :delete, data: {turbo_frame: "edit-add"}, onclick: "return confirm('Are you sure?');" do %>
              <%= image_tag "remove-icon.png" %>
            <% end %>
          <% end%>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/groups/new.html.erb
<%= turbo_frame_tag "edit-add" do%>
  <div class="outer">
    <%= form_for(@group) do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, autocomplete: "off" %>
        <% if @group.errors[:name].any? %>
          <div class="text-danger">
            <%= @group.errors[:name].join(', ') %>
          </div>
        <% end %>
      </div>

      <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
        <% if @group.errors[:description].any? %>
          <div class="text-danger">
            <%= @group.errors[:description].join(', ') %>
          </div>
        <% end %>
      </div>

      <%= f.submit %>
    <% end %>
  </div>
<% end %>

app/views/groups/search.html.erb
<%= turbo_frame_tag "participants-frame" do%>
  <% @search.each do |user|%>
    <div class="user-search-grp">
      <div class= "user-search-avatar">
        <% if user.avatar.present?%>
          <%= image_tag url_for(user.avatar) %>
        <% else %>
          <% if user.gender == "male"%>
            <%= image_tag "male_avatar.png" %>
          <% else %>
            <%= image_tag "female_avatar.png" %>
          <% end %>
        <% end %>
      </div>

      <div class="user-search-content">
        <div class="user-search-name"> 
          <%= user.name %>
        </div>
        <div class="user-search-email"> 
          <%= user.email %>
        </div>
      </div>
      
      <% if current_user.id == @group.admin_id %>
        <%= button_to add_user_group_path(@group, user_id: user.id),
          method: :post, data: {turbo_frame: "edit-add"} do %>
          <%= image_tag "add_new.png" %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/groups/show.html.erb
<%= turbo_frame_tag "edit-add" do%>
  <div class="edit-add-container">
      <div class="grp-msg" >
        <div id="new-msg">
        </div>
        
        <div>
          <% @group.messages.each do |msg|%>
            <%= render partial: "partial/message", locals: { msg: msg, sender: current_user } %>
          <% end %>
        </div>
      
      

        <div class="msg-send">
          <%= form_with(model: [@group, @group.messages.build], local: true, data: {turbo_frame: "edit-add"}) do |form| %>
            <%= form.hidden_field :receiver_type, value: "Group" %>
            <%= form.hidden_field :receiver_id, value: @group.id %> 
            <%= form.text_field :content, autocomplete: "off" %>
          
            <div class="send-attach">
              <%= form.file_field :images, multiple: true%>
              <%= form.submit "Send" %>
            </div>
          <% end %>
        </div>
      </div>
    

    <div class="info-bar">
      <div class= "info-bar-avatar">
        <%if @group.name.length == 3%>
          <%= image_tag "group1.png" %>
        <%elsif @group.name.length == 4%>
          <%= image_tag "group2.png" %>
        <%elsif @group.name.length == 5%>
          <%= image_tag "group3.png" %>
        <%elsif @group.name.length == 6%>
          <%= image_tag "group3.jpg" %>
        <%elsif @group.name.length == 7%>
          <%= image_tag "group5.jpeg" %>
        <%else%> 
          <%= image_tag "group6.jpeg" %>
        <%end%>
      </div>

      <div class= "info-bar-name">
        <%= @group.name %>
      </div>

      <div class= "info-bar-type">
        <%= (current_user.id == @group.admin_id) ? "Group Admin" : "Group User"%>
      </div>

      <% if current_user.id == @group.admin_id %>
        <div class= "info-bar-setting">
          <%= link_to edit_group_path, data: {turbo_frame: "space-content"} do%>
            <%= image_tag "settings2.png" %>
          <% end %>
        </div>
      <% end %>

      <% if current_user.id == @group.admin_id %>
        <div class= "info-bar-destroy">
          <%= link_to group_path(@group), data: {turbo_method: :delete}, onclick: "return confirm('Are you sure?');" do%>
            <%= image_tag "destroy.png" %>
          <% end %>
        </div>
      <% end %>

      <div class= "info-bar-participants">
        <%= link_to list_user_path, data: {turbo_frame: "space-content"} do%>
          <div>
            <%= image_tag "participants.png" %>
          </div>

          <div>
            Participants
          </div>
        <% end %>
      </div>

      <div class= "info-bar-space">
        <%= turbo_frame_tag "space-content" %>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="homepage">
  <div class="sidebar">
    <div class="top-item">
      <%= image_tag "biz.png" %>
    </div>
    <div class="middle-item">
      <%= link_to root_path, data: { turbo_frame: "_top"} do%>
        <%= image_tag "chat.png" %>
      <% end %>
    </div>
    <div class="buttom-item">
      <%= link_to edit_user_registration_path, data: { turbo_frame: "edit-add"} do %>
        <%= image_tag "settings.png" %>
      <% end %>
    </div>
  </div>

  <div class="left-section">
    <div class="left-item1">
      <div class="left-item1-chat">
        Chat
      </div>
      <div class="left-item1-avatar">
        <% if current_user.avatar.present? %>
          <%= image_tag current_user.avatar%>
        <% else %>
          <% if current_user.gender == "male"%>
            <%= image_tag "male_avatar.png" %>
          <% else %>
            <%= image_tag "female_avatar.png" %>
          <% end %>
        <% end%>
      </div>
      <div class="left-item1-name">
        <%= current_user.name%>
      </div>
    </div>

    <div class="left-item2">
      <div class="add-new1">
        <%= link_to new_group_path,  data: {turbo_frame: "edit-add"}  do %>
          <%= image_tag "add_new.png" %>
        <% end %>
      </div>
      <div class="left-item2-channels">
        Channels
      </div>
      <div class="left-item2-channel">
        <% current_user.groups.each do |group| %>
          <div class="group-lists">
            <%= link_to group_path(group), data: {turbo_frame: "edit-add" },
            class: "group-link", "data-group-id" => group.id do %>
              <%if group.name.length == 3%>
                <%= image_tag "group1.png" %>
              <%elsif group.name.length == 4%>
                <%= image_tag "group2.png" %>
              <%elsif group.name.length == 5%>
                <%= image_tag "group3.png" %>
              <%elsif group.name.length == 6%>
                <%= image_tag "group3.jpg" %>
              <%elsif group.name.length == 7%>
                <%= image_tag "group5.jpeg" %>
              <%else%> 
                <%= image_tag "group6.jpeg" %>
              <%end%>
            <% end%>
            <div class="group-name"> 
              <%= group.name%>
            </div>
          </div>
        <% end %>
      </div>
    </div>




    <div class="left-item3">
      <div class="left-item3-chats">
        Chats
      </div>
        <div class="left-item3-search">
          <%= form_for :search, url: 'home/search', method: :post do |f| %>
            <%= f.text_field :query, name: 'query', placeholder: 'Search', autocomplete: "off" %>
            <%= button_tag type: "submit", data: { turbo_frame: "search-frame"} do %>
              <%= image_tag "Magnifier.png" %>
            <% end %>
          <% end %>
      </div>
    </div>

    
    <div class="left-item4">
      <%= turbo_frame_tag "search-frame" do%>
        <div class="left-item4-all">
          All
        </div>
        <div class="chat-list">
          <% @msg_users.each do |u| %>
            <%= link_to home_path(u), data: {turbo_frame: "edit-add" } do %>
              <div class="conversation">
                <div class="left-item4-avatar">
                  <% if u.avatar.present?%>
                    <%= image_tag url_for(u.avatar) %>
                  <% else %>
                    <% if u.gender == "male"%>
                      <%= image_tag "male_avatar.png" %>
                    <% else %>
                      <%= image_tag "female_avatar.png" %>
                    <% end %>
                  <% end %>
                </div>
                <div class="left-item4-content">
                  <div class="left-item4-name">
                    <%= u.name %>
                  </div>
                  <div class="left-item4-msg">
                    <%=  !Message.find(u.latest_message_id).content.empty? ? Message.find(u.latest_message_id).content : "Photo message" %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>



  
  <div class="middle-section">
    <%= turbo_frame_tag "edit-add" do%>
      <div class="middle-section-content">
        No Conversations
      </div>
    <% end %>
  </div>

</div>

app/views/home/search.html.erb
<%= turbo_frame_tag "search-frame" do%>
  <% @search.each do |user|%>
    <%= link_to home_path(user), data: {turbo_frame: "edit-add" } do %>
      <div class="user-search">
        <div class= "user-search-avatar">
          <% if user.avatar.present?%>
            <%= image_tag url_for(user.avatar) %>
          <% else %>
            <% if user.gender == "male"%>
              <%= image_tag "male_avatar.png" %>
            <% else %>
              <%= image_tag "female_avatar.png" %>
            <% end %>
          <% end %>
        </div>
        <div class="user-search-content">
          <div class="user-search-name"> 
            <%= user.name %>
          </div>
          <div class="user-search-email"> 
            <%= user.email %>
          </div>
        </div>
        </div>
    <% end %>  
  <% end %>
<% end %>

app/views/home/show.html.erb
<%= turbo_frame_tag "edit-add" do%>
  <div class="edit-add-container">
    <div class="user-msg">
      <div id="latest-msg">
      </div>
      <% (current_user.messages + @user.messages).sort_by(&:created_at).reverse_each do |msg| %>
        <% if (msg.user_id == current_user.id && msg.receiver_id == @user.id) || 
              (msg.user_id == @user.id && msg.receiver_id == current_user.id) %>
          <%= render partial: "partial/message", locals: { msg: msg, sender: current_user} %>
        <% end %>
      <% end %>

      <div class="msg-send">
        <%= form_with(model: [@user, @user.messages.build], local: true) do |form| %>
          <%= form.hidden_field :receiver_type, value: "User" %>
          <%= form.hidden_field :receiver_id, value: @user.id %> 
          <%= form.text_field :content, autocomplete: "off" %>
          
          <div class="send-attach">
            <%= form.file_field :images, multiple: true %>
            <%= form.submit "Send", data: {turbo_frame: "edit-add"} %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="info-bar">
      <div class= "info-bar-avatar">
        <% if @user.avatar.present?%>
          <%= image_tag url_for(@user.avatar) %>
        <% else %>
          <% if @user.gender == "male"%>
            <%= image_tag "male_avatar.png" %>
          <% else %>
            <%= image_tag "female_avatar.png" %>
          <% end %>
        <% end %>
      </div>

      <div class= "info-bar-name">
        <%= @user.name %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sachin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <style>
      @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;1,400&display=swap');
    </style>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "users", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "homepage", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partial/_message.html.erb
<% if !msg.content.strip.empty? %>
  <div class="msg-display">
    <div class="<%= msg.user_id == sender.id ? 
    'msg-display-self' : 'msg-display-other' %>">

      <div class="msg-display-date">
        <%= msg.created_at.in_time_zone('Asia/Kathmandu').strftime("%-d %b, %Y %H:%M") %>
      </div>

      <div class="msg-display-content">
        <%= msg.content %>
      </div>

      <div class="msg-display-info">
        <div class="msg-display-avatar">
          <% if msg.user.avatar.present?%>
            <%= image_tag url_for(msg.user.avatar) %>
          <% else %>
            <% if msg.user.gender == "male"%>
              <%= image_tag "male_avatar.png" %>
            <% else %>
              <%= image_tag "female_avatar.png" %>
            <% end %>
          <% end %>
        </div>
        <div class="msg-display-name">
          <%= msg.user.name %>
        </div>
      </div>

    </div>
  </div>
<% end %>

<div class="msg-display">
  <% if msg.images.present? %>
    <div class="<%= msg.images.record.user_id == sender.id ? 
    'msg-display-self' : 'msg-display-other' %>">
      <div class="msg-display-date">
        <%= msg.images.record.created_at.in_time_zone('Asia/Kathmandu').strftime("%-d %b, %Y %H:%M") %>
      </div>

      <div class="img-send">
        <% msg.images.each do |img|%>
          <%= image_tag url_for(img) %>
        <% end %>
      </div>

      <div class="msg-display-info">
        <div class="msg-display-avatar">
          <% if msg.images.record.user.avatar.present?%>
            <%= image_tag url_for(msg.user.avatar) %>
          <% else %>
            <% if msg.images.record.user.gender == "male"%>
              <%= image_tag "male_avatar.png" %>
            <% else %>
              <%= image_tag "female_avatar.png" %>
            <% end %>
          <% end %>
        </div>
        <div class="msg-display-name">
          <%= msg.images.record.user.name %>
        </div>
      </div>
    </div>
  <% end %>
</div>